version: "2.2"

services:
  backend:
    build: ./backend
    container_name: my-backend
    ports:
      - "3001:3000"
    environment:
      NODE_ENV: production
      DB_USER: root
      DB_PASS: root
      DB_HOST: my-db
      DB_PORT: 3306
      DB_NAME: ecommerce
    command: sh -c "npm run db:migrate && npm start"
    depends_on:
      db:
        condition: service_healthy

  my-frontend:
    build: 
      context: ./frontend # Aponta para a pasta do frontend
      dockerfile: Dockerfile
    container_name: my-frontend
    ports:
      - "3000:3000" # Frontend acess√≠vel em localhost:3000
    environment:
      - API_URL=http://my-backend:3000
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    depends_on:
      - backend

  db:
    image: mysql:8.0
    container_name: my-db
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
