apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: ecommerce
type: Opaque
data:
  # Exemplo: se a senha for '14Jeronimo', o base64 Ã© 'MTRKZXJvbmltbw=='
  # Rode no terminal: echo -n "14Jeronimo" | base64
  # Rode no terminal: echo -n "cloudnative-db.xxxx.us-east-1.rds.amazonaws.com" | base64
  DB_PASS: "MTRKZXJvbmltbw=="
  DB_HOST: "ZWNvbW1lcmNlLWRiLmNrdjB5b3V1YWxtOS51cy1lYXN0LTEucmRzLmFtYXpvbmF3cy5jb20="